package com.eyedea.ui_component.compose.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.colorResource
import com.eyedea.ui_component.R

@Composable fun primaryBlack10() = colorResource(id = R.color.primary_black_10)
@Composable fun primaryBlack100() = colorResource(id = R.color.primary_black_100)
@Composable fun primaryBlack200() = colorResource(id = R.color.primary_black_200)
@Composable fun primaryBlack300() = colorResource(id = R.color.primary_black_300)
@Composable fun primaryBlack400() = colorResource(id = R.color.primary_black_400)
@Composable fun primaryBlack500() = colorResource(id = R.color.primary_black_500)
@Composable fun primaryBlack600() = colorResource(id = R.color.primary_black_600)
@Composable fun primaryBlack700() = colorResource(id = R.color.primary_black_700)
@Composable fun primaryBlack800() = colorResource(id = R.color.primary_black_800)
@Composable fun primaryBlack900() = colorResource(id = R.color.primary_black_900)

val PrimaryBlack10 = Color(0xFFFAFAFA)
val PrimaryBlack100 = Color(0xFFF3F3F3)
val PrimaryBlack200 = Color(0xFFE8E8E8)
val PrimaryBlack300 = Color(0xFFBABABA)
val PrimaryBlack400 = Color(0xFF767676)
val PrimaryBlack500 = Color(0xFF1B1B1B)
val PrimaryBlack600 = Color(0xFF171314)
val PrimaryBlack700 = Color(0xFF130D0E)
val PrimaryBlack800 = Color(0xFF0F080A)
val PrimaryBlack900 = Color(0xFF0C0507)

@Composable fun primaryInformation100() = colorResource(id = R.color.primary_information_100)
@Composable fun primaryInformation200() = colorResource(id = R.color.primary_information_200)
@Composable fun primaryInformation300() = colorResource(id = R.color.primary_information_300)
@Composable fun primaryInformation400() = colorResource(id = R.color.primary_information_400)
@Composable fun primaryInformation500() = colorResource(id = R.color.primary_information_500)
@Composable fun primaryInformation600() = colorResource(id = R.color.primary_information_600)
@Composable fun primaryInformation700() = colorResource(id = R.color.primary_information_700)
@Composable fun primaryInformation800() = colorResource(id = R.color.primary_information_800)
@Composable fun primaryInformation900() = colorResource(id = R.color.primary_information_900)

@Composable fun primarySuccess100() = colorResource(id = R.color.primary_success_100)
@Composable fun primarySuccess200() = colorResource(id = R.color.primary_success_200)
@Composable fun primarySuccess300() = colorResource(id = R.color.primary_success_300)
@Composable fun primarySuccess400() = colorResource(id = R.color.primary_success_400)
@Composable fun primarySuccess500() = colorResource(id = R.color.primary_success_500)
@Composable fun primarySuccess600() = colorResource(id = R.color.primary_success_600)
@Composable fun primarySuccess700() = colorResource(id = R.color.primary_success_700)
@Composable fun primarySuccess800() = colorResource(id = R.color.primary_success_800)
@Composable fun primarySuccess900() = colorResource(id = R.color.primary_success_900)

val PrimarySuccess100 = Color(0xFFD1FCDA)
val PrimarySuccess200 = Color(0xFFA5F9BF)
val PrimarySuccess300 = Color(0xFF76EFA8)
val PrimarySuccess400 = Color(0xFF52E09B)
val PrimarySuccess500 = Color(0xFF20CC89)
val PrimarySuccess600 = Color(0xFF17AF83)
val PrimarySuccess700 = Color(0xFF109279)
val PrimarySuccess800 = Color(0xFF0A766C)
val PrimarySuccess900 = Color(0xFF066161)

@Composable fun primaryError100() = colorResource(id = R.color.primary_error_100)
@Composable fun primaryError200() = colorResource(id = R.color.primary_error_200)
@Composable fun primaryError300() = colorResource(id = R.color.primary_error_300)
@Composable fun primaryError400() = colorResource(id = R.color.primary_error_400)
@Composable fun primaryError500() = colorResource(id = R.color.primary_error_500)
@Composable fun primaryError600() = colorResource(id = R.color.primary_error_600)
@Composable fun primaryError700() = colorResource(id = R.color.primary_error_700)
@Composable fun primaryError800() = colorResource(id = R.color.primary_error_800)
@Composable fun primaryError900() = colorResource(id = R.color.primary_error_900)

val PrimaryError100 = Color(0xFFFEEAD2)
val PrimaryError200 = Color(0xFFFED0A5)
val PrimaryError300 = Color(0xFFFEAF78)
val PrimaryError400 = Color(0xFFFD8F56)
val PrimaryError500 = Color(0xFFFD5B1F)
val PrimaryError600 = Color(0xFFD93D16)
val PrimaryError700 = Color(0xFFB6250F)
val PrimaryError800 = Color(0xFF921209)
val PrimaryError900 = Color(0xFF790506)
